### ISSUE TITLE
Don't run app

### ISSUE THREAD

**Issue by ilyasov-il** [GarikFirst/PyParkingBot#3]
`root@Ubuntu-1804-bionic-64-minimal ~/PyParkingBot # python3 -c config-sample.json
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'config' is not defined`

**Comment by GarikFirst** [comment]
Oh, there was mistake in launch command it should be `python3 parking_bot.py -c CONFIG-FILE`, fixed in readme
